reduce_dim: !!python/object:sklearn.decomposition._pca.PCA
  _sklearn_version: 1.3.1
  copy: true
  iterated_power: auto
  n_components: 6
  n_oversamples: 10
  power_iteration_normalizer: auto
  random_state: null
  svd_solver: auto
  tol: 0.0
  whiten: false
regresor: !!python/object:sklearn.ensemble._gb.GradientBoostingRegressor
  _sklearn_version: 1.3.1
  alpha: 0.9
  ccp_alpha: 0.0
  criterion: friedman_mse
  init: null
  learning_rate: 0.1
  loss: squared_error
  max_depth: 3
  max_features: null
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 100
  n_iter_no_change: null
  random_state: null
  subsample: 1.0
  tol: 0.0001
  validation_fraction: 0.1
  verbose: 0
  warm_start: false
regresor__criterion: friedman_mse
regresor__learning_rate: 0.1
regresor__max_depth: 4
regresor__n_estimators: 200
scaler: null
